import type { Subject } from './contract/school';

/**
 * كتالوج المواد الافتراضي (SUB في النموذج الأولي): المواد العامة للمنصة (subjects.school_id = NULL).
 * مولَّد من fixtures/scenarios/6.5-1-demo.json — نفس قيم النموذج الأولي.
 */
export const DEFAULT_SUBJECTS: readonly Subject[] = [
  {
    key: 'ar',
    name: 'اللغة العربية',
    short: 'العربية',
    default_hours: 4,
    hue: 12,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'fr',
    name: 'اللغة الفرنسية',
    short: 'الفرنسية',
    default_hours: 4,
    hue: 212,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'ma',
    name: 'الرياضيات',
    short: 'الرياضيات',
    default_hours: 4,
    hue: 268,
    no_daily_cap: false,
    hard: true,
    prefer_double: false,
  },
  {
    key: 'pc',
    name: 'الفيزياء والكيمياء',
    short: 'الفيزياء',
    default_hours: 2,
    hue: 188,
    no_daily_cap: false,
    hard: true,
    prefer_double: false,
  },
  {
    key: 'svt',
    name: 'علوم الحياة والأرض',
    short: 'علوم الحياة',
    default_hours: 2,
    hue: 128,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'hg',
    name: 'الاجتماعيات',
    short: 'الاجتماعيات',
    default_hours: 2,
    hue: 36,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'en',
    name: 'اللغة الإنجليزية',
    short: 'الإنجليزية',
    default_hours: 2,
    hue: 330,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'inf',
    name: 'الإعلاميات',
    short: 'الإعلاميات',
    default_hours: 1,
    hue: 245,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'eps',
    name: 'التربية البدنية',
    short: 'التربية البدنية',
    default_hours: 2,
    hue: 92,
    no_daily_cap: false,
    hard: false,
    prefer_double: true,
  },
  {
    key: 'ei',
    name: 'التربية الإسلامية',
    short: 'التربية الإسلامية',
    default_hours: 1,
    hue: 160,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'eco',
    name: 'الاقتصاد العام والإحصاء',
    short: 'الاقتصاد العام',
    default_hours: 4,
    hue: 300,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'cpt',
    name: 'المحاسبة والرياضيات المالية',
    short: 'المحاسبة',
    default_hours: 4,
    hue: 55,
    no_daily_cap: true,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'org',
    name: 'الاقتصاد والتنظيم الإداري للمقاولات',
    short: 'التنظيم الإداري',
    default_hours: 3,
    hue: 0,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
  {
    key: 'phi',
    name: 'الفلسفة',
    short: 'الفلسفة',
    default_hours: 2,
    hue: 75,
    no_daily_cap: false,
    hard: false,
    prefer_double: false,
  },
];
